# Generated by Django 4.0.1 on 2022-03-13 10:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Kategoriya nomi')),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Places',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Joy nomi')),
                ('vote', models.PositiveIntegerField(verbose_name='Bu joyga ovoz berish')),
                ('percent', models.FloatField(verbose_name='Reytingi')),
                ('date', models.DateField(auto_now_add=True)),
                ('bind', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vote.category')),
            ],
        ),
    ]
