# Generated by Django 4.0.1 on 2022-03-13 15:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vote', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='places',
            options={'ordering': ['-id']},
        ),
    ]
